{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secretName is required when secretEnv is set" .Values.secretName }}
  labels:
    {{- include "xprem.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
