#!/usr/bin/env bash
# Idempotent repository bootstrap for the xprem Cloud Agent dev environment.
#
# Runs once when the environment build/snapshot is created (and again if the
# environment is rebuilt). It installs the system services the control plane
# needs (PostgreSQL + ClickHouse), the Go hot-reload tool, all Go modules, and
# builds the dashboard. Per-boot service startup lives in start.sh; the running
# apps live in the environment.json terminals.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export DEBIAN_FRONTEND=noninteractive

echo "==> [install] apt update"
sudo apt-get update -y

echo "==> [install] PostgreSQL"
if ! command -v psql >/dev/null 2>&1; then
  sudo apt-get install -y postgresql postgresql-contrib
else
  echo "    PostgreSQL already installed"
fi

echo "==> [install] ClickHouse"
if ! command -v clickhouse >/dev/null 2>&1; then
  sudo apt-get install -y apt-transport-https ca-certificates dirmngr gnupg curl
  # ClickHouse signs its apt repo with this key. Fetch it to a keyring file
  # (piping straight into sudo gpg fails under a non-interactive shell).
  curl -fsSL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3E4AD4719DDE9A38' -o /tmp/clickhouse.key.asc
  sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg /tmp/clickhouse.key.asc
  sudo chmod +r /usr/share/keyrings/clickhouse-keyring.gpg
  ARCH="$(dpkg --print-architecture)"
  echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg arch=${ARCH}] https://packages.clickhouse.com/deb stable main" \
    | sudo tee /etc/apt/sources.list.d/clickhouse.list >/dev/null
  sudo apt-get update -y
  # The clickhouse-server postinst runs `clickhouse install`, which prompts for
  # the default user's password whenever it can open a controlling terminal
  # (DEBIAN_FRONTEND=noninteractive does not suppress it). `setsid --wait ...
  # < /dev/null` detaches the process from any tty, so the prompt is skipped and
  # the default user is left with an empty password (fine for local dev). This
  # keeps the install non-interactive whether or not a tty is attached.
  sudo DEBIAN_FRONTEND=noninteractive setsid --wait \
    apt-get install -y clickhouse-server clickhouse-client < /dev/null
else
  echo "    ClickHouse already installed"
fi

echo "==> [install] Go hot-reload tool (reflex)"
# Pinned to a tested release so repeated installs are reproducible.
go install github.com/cespare/reflex@v0.3.2

echo "==> [install] Go modules"
go mod download

echo "==> [install] Dashboard dependencies + build"
( cd apps/dashboard && npm ci && npm run build )

echo "==> [install] Local .env"
# The .env holds three secrets that must stay in lock-step with data persisted
# in the PostgreSQL data directory: ADMIN_PASSWORD (hashed once into the users
# table by the seed-first-admin migration), DB_KEYS_MASTER_KEY_B64 (seals every
# app's Expo signing key in the DB), and JWT_SECRET (signs live dashboard
# sessions). Because .env is git-ignored, a fresh git checkout — which is
# exactly what an environment build or a snapshot-backed boot does — drops it,
# and naive regeneration would mint NEW secrets while the old ones remain baked
# into the persisted DB: the seeded admin could no longer log in, and sealed
# signing keys could no longer be decrypted. To keep them in sync we persist a
# copy outside the repo (which survives re-checkouts on the same disk) and
# restore it instead of regenerating whenever the repo .env is missing.
# These files hold live secrets, so keep them owner-only (0600) and the backup
# directory owner-only (0700); a 022 umask would otherwise leave them readable
# by any other local account.
ENV_BACKUP="${HOME}/.xprem/dev.env"
if [ ! -f .env ] && [ -f "$ENV_BACKUP" ]; then
  install -m 600 "$ENV_BACKUP" .env
  echo "    restored .env from ${ENV_BACKUP} (keeps secrets in sync with the persisted DB)"
fi
if [ ! -f .env ]; then
  JWT_SECRET="$(openssl rand -hex 32)"
  MASTER_KEY="$(openssl rand -base64 32)"
  # Random admin password, unique per environment. The suffix guarantees the
  # dashboard password policy (>=8 chars, upper, lower, digit, special char)
  # is always met. Developers read the value from the generated .env below.
  ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9')Aa1!"
  cat > .env <<EOF
# Auto-generated by .cursor/install.sh for local development (control-plane / DB mode).
# Safe to edit; git-ignored. Generated once, then backed up to ~/.xprem/dev.env
# and restored from there on later checkouts so the admin login and sealed app
# keys keep matching the persisted database. To mint fresh secrets, delete both
# this file and ~/.xprem/dev.env (and reset the database).
PORT=3000
BASE_URL=http://localhost:3000

# Storage: local filesystem bucket
STORAGE_MODE=local
LOCAL_BUCKET_BASE_PATH=./updates

# Dashboard / control-plane API surface (auth, apps, branches, channels, rollouts)
USE_DASHBOARD=true

# Auth
JWT_SECRET=${JWT_SECRET}

# Control plane (PostgreSQL)
DB_URL=postgres://postgres:postgres@127.0.0.1:5432/xprem_dev?sslmode=disable
# Master key that seals per-app Expo signing keys stored in Postgres
DB_KEYS_MASTER_KEY_B64=${MASTER_KEY}

# Observe (ClickHouse): telemetry, metrics, logs
CLICKHOUSE_URL=clickhouse://default@127.0.0.1:9000/xprem_dev

# First dashboard admin, seeded once by the control-plane migration.
# The password is randomly generated per environment; read it from this file
# and log in at http://localhost:5173/dashboard.
ADMIN_EMAIL=admin@xprem.dev
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Expose Prometheus metrics at /metrics
PROMETHEUS_ENABLED=true

# Never phone home in local dev
DISABLE_TELEMETRY=true
EOF
  echo "    wrote .env (secrets generated)"
fi
# Enforce owner-only perms whether .env was just generated, restored, or
# hand-edited by the developer.
chmod 600 .env

# Mirror the current .env to the persistent backup so a later fresh checkout
# restores these exact secrets instead of minting new ones. Idempotent: only
# copies when the backup is missing or has drifted from the repo .env.
install -d -m 700 "$(dirname "$ENV_BACKUP")"
if [ ! -f "$ENV_BACKUP" ] || ! cmp -s .env "$ENV_BACKUP"; then
  install -m 600 .env "$ENV_BACKUP"
  echo "    backed up .env to ${ENV_BACKUP}"
fi
chmod 600 "$ENV_BACKUP"

echo "==> [install] done"
