#!/usr/bin/env bash
# Idempotent repository bootstrap for the xprem Cloud Agent dev environment.
#
# Runs once when the environment build/snapshot is created (and again if the
# environment is rebuilt). It installs the system services the control plane
# needs (PostgreSQL + ClickHouse), the Go hot-reload tool, all Go modules, and
# builds the dashboard. Per-boot service startup lives in start.sh; the running
# apps live in the environment.json terminals.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export DEBIAN_FRONTEND=noninteractive

echo "==> [install] apt update"
sudo apt-get update -y

echo "==> [install] PostgreSQL"
if ! command -v psql >/dev/null 2>&1; then
  sudo apt-get install -y postgresql postgresql-contrib
else
  echo "    PostgreSQL already installed"
fi

echo "==> [install] ClickHouse"
if ! command -v clickhouse >/dev/null 2>&1; then
  sudo apt-get install -y apt-transport-https ca-certificates dirmngr gnupg curl
  # ClickHouse signs its apt repo with this key. Fetch it to a keyring file
  # (piping straight into sudo gpg fails under a non-interactive shell).
  curl -fsSL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3E4AD4719DDE9A38' -o /tmp/clickhouse.key.asc
  sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg /tmp/clickhouse.key.asc
  sudo chmod +r /usr/share/keyrings/clickhouse-keyring.gpg
  ARCH="$(dpkg --print-architecture)"
  echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg arch=${ARCH}] https://packages.clickhouse.com/deb stable main" \
    | sudo tee /etc/apt/sources.list.d/clickhouse.list >/dev/null
  sudo apt-get update -y
  sudo apt-get install -y clickhouse-server clickhouse-client
else
  echo "    ClickHouse already installed"
fi

echo "==> [install] Go hot-reload tool (reflex)"
go install github.com/cespare/reflex@latest

echo "==> [install] Go modules"
go mod download

echo "==> [install] Dashboard dependencies + build"
( cd apps/dashboard && npm ci && npm run build )

echo "==> [install] Local .env"
if [ ! -f .env ]; then
  JWT_SECRET="$(openssl rand -hex 32)"
  MASTER_KEY="$(openssl rand -base64 32)"
  cat > .env <<EOF
# Auto-generated by .cursor/install.sh for local development (control-plane / DB mode).
# Safe to edit or delete; it is git-ignored and regenerated when missing.
PORT=3000
BASE_URL=http://localhost:3000

# Storage: local filesystem bucket
STORAGE_MODE=local
LOCAL_BUCKET_BASE_PATH=./updates

# Dashboard / control-plane API surface (auth, apps, branches, channels, rollouts)
USE_DASHBOARD=true

# Auth
JWT_SECRET=${JWT_SECRET}

# Control plane (PostgreSQL)
DB_URL=postgres://postgres:postgres@127.0.0.1:5432/xprem_dev?sslmode=disable
# Master key that seals per-app Expo signing keys stored in Postgres
DB_KEYS_MASTER_KEY_B64=${MASTER_KEY}

# Observe (ClickHouse): telemetry, metrics, logs
CLICKHOUSE_URL=clickhouse://default@127.0.0.1:9000/xprem_dev

# First dashboard admin, seeded once by the control-plane migration.
# Log in at http://localhost:5173/dashboard with these credentials.
ADMIN_EMAIL=admin@xprem.dev
ADMIN_PASSWORD=Admin!2345

# Expose Prometheus metrics at /metrics
PROMETHEUS_ENABLED=true

# Never phone home in local dev
DISABLE_TELEMETRY=true
EOF
  echo "    wrote .env (secrets generated)"
else
  echo "    .env already present, leaving it untouched"
fi

echo "==> [install] done"
