// Renders and validates the Helm deployment pair for the chart (helm/ in the
// server repository): values.yaml carries the toggles and the structure of the
// environment list (committable, no secret), secrets.yaml is a values overlay
// holding every value in the secretEnv map. The chart renders that map into
// the secretName Secret, so one `helm install -f values.yaml -f secrets.yaml`
// deploys everything.

import { load as loadYaml } from 'js-yaml';

import { type ServerChoices, needsAwsAccessKeys } from './choices';
import { ENV_SECTIONS, type ValidationIssue, isPlaceholder, validateEnvMap } from './envCatalog';
import { missingPasswordRules } from './passwordPolicy';

export const HELM_SECRET_NAME = 'xprem-secrets';
export const HELM_SECRETS_FILE = 'secrets.yaml';

// The chart injects PROMETHEUS_ENABLED from podAnnotations, never from the
// environment list; computed vars (helmKey) come from the values toggles.
const CHART_OWNED_VARS = new Set(['PROMETHEUS_ENABLED']);

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function ingressHost(choices: ServerChoices): string {
  if (choices.baseUrl) {
    try {
      return new URL(choices.baseUrl).hostname;
    } catch {
      // Fall through to the placeholder.
    }
  }
  return '<your-ota-domain>';
}

/** Renders the values.yaml content: toggles and structure, no secret values. */
export function renderHelmValues(choices: ServerChoices): string {
  const host = ingressHost(choices);
  const lines: string[] = [
    '# Generated by eoas server:init. Safe to commit: every value lives in',
    `# ${HELM_SECRETS_FILE} (gitignored), which the chart renders into the`,
    `# "${HELM_SECRET_NAME}" Secret. Deploy both files together:`,
    `#   helm install xprem <chart> -f values.yaml -f ${HELM_SECRETS_FILE} -n <namespace>`,
    '# Check the pair with: eoas server:validate <this directory>',
    '# Values not listed here keep the chart defaults.',
    '',
    `replicaCount: ${choices.replicas === 'multi' ? 3 : 1}`,
    '',
    `secretName: ${yamlString(HELM_SECRET_NAME)}`,
    '',
    'controlPlane: "true"',
    `dbKeysMasterKeySource: ${yamlString(choices.masterKeySource)}`,
    '# Also selects the CloudFront private-key source.',
    `keysStorageType: ${yamlString(
      choices.masterKeySource === 'aws-secrets-manager' ? 'aws-secrets-manager' : 'environment'
    )}`,
    `storageMode: ${yamlString(
      choices.storage === 'gcs' ? 'gcs' : choices.storage === 'azure' ? 'azure' : 's3'
    )}`,
    `cacheMode: ${yamlString(choices.cacheMode)}`,
    'useDashboard: "true"',
    `useCloudfrontRedirect: "${choices.delivery === 'cloudfront'}"`,
    `useGenericCDN: "${choices.delivery === 'generic-cdn'}"`,
    `useAWSAccessKeys: "${needsAwsAccessKeys(choices)}"`,
    '',
  ];

  if (
    choices.awsAuth === 'iam-role' &&
    (choices.storage === 'aws-s3' || choices.masterKeySource === 'aws-secrets-manager')
  ) {
    lines.push(
      'serviceAccount:',
      '  create: true',
      '  name: "xprem-sa"',
      '  # On EKS, bind the IAM role through the service account (IRSA):',
      '  annotations: {}',
      '    # eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/xprem-storage"',
      ''
    );
  }

  lines.push(
    '# Which env vars the pod gets. Values come from the secret; optional entries',
    `# are read from it only when present. Fill the values in ${HELM_SECRETS_FILE}.`,
    'environment:'
  );
  for (const section of ENV_SECTIONS) {
    const vars = section.vars.filter(
      spec => spec.applies(choices) && !CHART_OWNED_VARS.has(spec.name)
    );
    for (const spec of vars) {
      if (spec.helmKey) {
        lines.push(
          `  - name: ${yamlString(spec.name)}`,
          `    key: ${yamlString(spec.helmKey)}`,
          '    required: true',
          '    computed: true'
        );
      } else if (spec.required) {
        lines.push(`  - name: ${yamlString(spec.name)}`, '    required: true');
      } else {
        lines.push(
          `  - name: ${yamlString(spec.name)}`,
          '    enabled: true',
          '    required: false'
        );
      }
    }
  }

  lines.push(
    '',
    'podAnnotations: {}',
    '  # prometheus.io/scrape: "true"',
    '',
    'ingress:',
    '  enabled: true',
    '  className: ""',
    '  hosts:',
    `    - host: ${yamlString(host)}`,
    '      paths:',
    '        - path: /',
    '          pathType: Prefix',
    '  tls:',
    '    - secretName: xprem-tls',
    '      hosts:',
    `        - ${yamlString(host)}`,
    ''
  );

  return lines.join('\n');
}

/**
 * Renders the secrets.yaml content: a values overlay whose secretEnv map the
 * chart turns into the secretName Secret. Every non-computed value lands
 * here; optional vars stay commented out.
 */
export function renderHelmSecretsValues(choices: ServerChoices): string {
  const lines: string[] = [
    '# Generated by eoas server:init. Do NOT commit this file; gitignore it.',
    '# Fill every <placeholder>, then deploy it together with values.yaml:',
    `#   helm install xprem <chart> -f values.yaml -f ${HELM_SECRETS_FILE} -n <namespace>`,
    '# To change a value later, edit it here and run helm upgrade with the same',
    '# flags: the chart re-rolls the pods automatically.',
    'secretEnv:',
  ];
  for (const section of ENV_SECTIONS) {
    const vars = section.vars.filter(
      spec => spec.applies(choices) && !CHART_OWNED_VARS.has(spec.name) && !spec.helmKey
    );
    const note = section.note?.(choices);
    if (vars.length === 0) {
      continue;
    }
    lines.push(`  # ----- ${section.title} -----`);
    if (note) {
      lines.push(`  # ${note}`);
    }
    for (const spec of vars) {
      if (spec.comment) {
        lines.push(`  # ${spec.comment}`);
      }
      const assignment = `${spec.name}: ${yamlString(spec.value(choices))}`;
      lines.push(spec.required ? `  ${assignment}` : `  # ${assignment}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

/** The secretEnv map of a values document, when it carries one. */
export function extractSecretEnv(doc: Record<string, unknown>): Record<string, string> | undefined {
  const secretEnv = doc.secretEnv;
  if (!secretEnv || typeof secretEnv !== 'object' || Array.isArray(secretEnv)) {
    return undefined;
  }
  const env: Record<string, string> = {};
  for (const [key, value] of Object.entries(secretEnv as Record<string, unknown>)) {
    env[key] = String(value ?? '');
  }
  return env;
}

type HelmEnvEntry = {
  name?: string;
  value?: unknown;
  key?: string;
  computed?: boolean;
};

export function parseYamlFile(content: string): Record<string, unknown> {
  const parsed = loadYaml(content);
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('The file does not contain a YAML mapping.');
  }
  return parsed as Record<string, unknown>;
}

/** True for a YAML mapping that plausibly is a values file for the chart. */
export function looksLikeChartValues(doc: Record<string, unknown>): boolean {
  return ['controlPlane', 'storageMode', 'cacheMode', 'secretName', 'environment'].some(
    key => key in doc
  );
}

/** The env the pod would see: the secret env plus the computed toggle vars. */
function envFromPair(
  values: Record<string, unknown>,
  secretEnv: Record<string, string> | undefined
): Record<string, string> {
  const env: Record<string, string> = { ...secretEnv };
  const entries = Array.isArray(values.environment) ? (values.environment as HelmEnvEntry[]) : [];
  for (const entry of entries) {
    if (entry && typeof entry === 'object' && entry.name && entry.computed && entry.key) {
      env[entry.name] = String(values[entry.key] ?? '');
    }
  }
  return env;
}

/**
 * Validates a values/secret-env pair. Either side can be missing: the checks
 * that need the other half are skipped and replaced with an issue saying so.
 */
export function validateHelmPair(
  values: Record<string, unknown> | undefined,
  secretEnv: Record<string, string> | undefined
): ValidationIssue[] {
  if (!values) {
    return [
      {
        level: 'warning',
        message:
          'No chart values file found next to the secrets overlay: toggles are unknown, only the secret values themselves were checked.',
      },
      ...validateSecretValues(secretEnv ?? {}),
    ];
  }

  if (String(values.controlPlane) !== 'true') {
    return [
      {
        level: 'warning',
        message:
          'controlPlane is not "true": server:validate only checks control-plane configurations, nothing was verified.',
      },
    ];
  }

  const issues: ValidationIssue[] = [];
  if (!secretEnv) {
    issues.push({
      level: 'error',
      message: `No ${HELM_SECRETS_FILE} with a secretEnv map found next to the values file: it holds the environment values the chart renders into the "${String(
        values.secretName ?? HELM_SECRET_NAME
      )}" Secret.`,
    });
  } else {
    issues.push(
      ...validateEnvMap(envFromPair(values, secretEnv), {
        masterKeySource:
          String(values.dbKeysMasterKeySource) === 'aws-secrets-manager'
            ? 'aws-secrets-manager'
            : 'environment',
        ...(String(values.useCloudfrontRedirect) === 'true'
          ? { delivery: 'cloudfront' as const }
          : String(values.useGenericCDN) === 'true'
            ? { delivery: 'generic-cdn' as const }
            : {}),
      })
    );
  }

  const replicaCount = Number(values.replicaCount ?? 1);
  if (replicaCount > 1) {
    if (String(values.cacheMode) === 'local') {
      issues.push({
        level: 'error',
        message: `replicaCount is ${replicaCount} with cacheMode "local": replicas need a shared cache, use redis or redis-sentinel.`,
      });
    }
    if (String(values.storageMode) === 'local') {
      issues.push({
        level: 'error',
        message: `replicaCount is ${replicaCount} with storageMode "local": local storage cannot be shared between replicas.`,
      });
    }
  }

  const env = secretEnv ? envFromPair(values, secretEnv) : {};
  if (String(values.useCloudfrontRedirect) !== 'true' && env.CLOUDFRONT_DOMAIN) {
    issues.push({
      level: 'warning',
      message: 'CLOUDFRONT_DOMAIN is set but useCloudfrontRedirect is not "true".',
    });
  }
  if (String(values.useGenericCDN) !== 'true' && env.CDN_BASE_URL) {
    issues.push({
      level: 'warning',
      message: 'CDN_BASE_URL is set but useGenericCDN is not "true"; the chart will not render it.',
    });
  }

  const ingress = values.ingress as { hosts?: { host?: string }[] } | undefined;
  const host = ingress?.hosts?.[0]?.host;
  if (host && env.BASE_URL && !isPlaceholder(env.BASE_URL) && !isPlaceholder(host)) {
    try {
      if (new URL(env.BASE_URL).hostname !== host) {
        issues.push({
          level: 'warning',
          message: `BASE_URL (${env.BASE_URL}) does not match the ingress host (${host}).`,
        });
      }
    } catch {
      // BASE_URL validity is already reported by validateEnvMap.
    }
  }

  return issues;
}

/**
 * Value-level checks for a secret env validated alone: without the values
 * file the applicable variable set is unknown, so only what can be judged
 * from the values themselves is checked.
 */
function validateSecretValues(env: Record<string, string>): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  const lenientVars = new Set(
    ENV_SECTIONS.flatMap(section => section.vars.filter(spec => spec.lenient)).map(
      spec => spec.name
    )
  );
  for (const [name, value] of Object.entries(env)) {
    if (isPlaceholder(value)) {
      issues.push({
        level: lenientVars.has(name) ? 'warning' : 'error',
        message: `${name} is still a placeholder: ${value}`,
      });
    }
  }
  if (env.DB_KEYS_MASTER_KEY_B64 && env.AWSSM_DB_KEYS_MASTER_KEY_SECRET_ID) {
    issues.push({
      level: 'error',
      message:
        'Both DB_KEYS_MASTER_KEY_B64 and AWSSM_DB_KEYS_MASTER_KEY_SECRET_ID are set; the server requires exactly one master key source.',
    });
  }
  if (!!env.MAXMIND_ACCOUNT_ID !== !!env.MAXMIND_LICENSE_KEY) {
    issues.push({
      level: 'error',
      message:
        'MAXMIND_ACCOUNT_ID and MAXMIND_LICENSE_KEY must be set together; the server refuses to start with only one of them.',
    });
  }
  if (env.ADMIN_PASSWORD && !isPlaceholder(env.ADMIN_PASSWORD)) {
    const missing = missingPasswordRules(env.ADMIN_PASSWORD);
    if (missing.length > 0) {
      issues.push({
        level: 'error',
        message: `ADMIN_PASSWORD does not meet the dashboard password policy, it needs ${missing.join(
          ', '
        )}. The first boot fails otherwise.`,
      });
    }
  }
  return issues;
}
