package mcptools

import (
	"context"
	"errors"
	"log"
	"strings"
	"xprem/config"
	"xprem/internal/services"

	mcpprot "github.com/modelcontextprotocol/go-sdk/mcp"
)

// appCreateAccess has no permission string: creating an app is account-wide,
// admin only, like its dashboard route (POST /apps behind adminOnly).
var appCreateAccess = Access{Fallback: FallbackAdminOnly}

type CreateAppInput struct {
	Name string `json:"name" jsonschema:"the display name of the new app"`
}

type CreateAppOutput struct {
	AppId string `json:"appId"`
	Name  string `json:"name"`
}

func createAppHandler(deps Deps) func(ctx context.Context, req *mcpprot.CallToolRequest, input CreateAppInput) (*mcpprot.CallToolResult, CreateAppOutput, error) {
	return func(ctx context.Context, req *mcpprot.CallToolRequest, input CreateAppInput) (*mcpprot.CallToolResult, CreateAppOutput, error) {
		principal := PrincipalFromRequest(req)
		if principal == nil {
			return nil, CreateAppOutput{}, errors.New("no authenticated account on this session")
		}
		// No app exists yet to authorize against, so the gate is the account
		// role itself, as on the dashboard route.
		if !principal.IsAdmin {
			return nil, CreateAppOutput{}, errors.New("creating an app requires an admin account")
		}
		name := strings.TrimSpace(input.Name)
		if name == "" {
			return nil, CreateAppOutput{}, errors.New("name is required")
		}
		// Keys are generated by the server and sealed in the database, the
		// dashboard's default: nothing to provision, and get_certificate
		// hands out the certificate the app build embeds.
		// The principal-bearing ctx is what the audit log records as actor.
		keysConfig := config.KeysConfig{Mode: config.KeysModeDatabase}
		appId, err := deps.AppCreator.CreateApp(services.WithPrincipal(ctx, principal), name, keysConfig)
		if err != nil {
			return nil, CreateAppOutput{}, writeError(err, "create the app", "mcp create_app", principal, "")
		}
		if deps.OnAppsChanged != nil {
			deps.OnAppsChanged()
		}
		log.Printf("mcp create_app: user %s created app %s (%s)", principal.UserId, appId, name)
		return nil, CreateAppOutput{AppId: appId, Name: name}, nil
	}
}

func registerCreateApp(server *mcpprot.Server, deps Deps) {
	mcpprot.AddTool(server, &mcpprot.Tool{
		Name:        "create_app",
		Description: "Create an app (name required). Its code-signing keys are generated by the server and sealed in the database; fetch the certificate to embed in the app build with get_certificate, then create its branches and channels. Requires an admin account.",
		Annotations: &mcpprot.ToolAnnotations{
			Title:           "Create app",
			DestructiveHint: boolPtr(false),
			IdempotentHint:  false,
		},
	}, createAppHandler(deps))
}
