package store

import (
	"context"
	"expo-open-ota/internal/database"
	"expo-open-ota/internal/database/postgres/pgdb"
	"expo-open-ota/internal/types"
	"fmt"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PostgresRolloutStore struct {
	engine *database.Engine
}

func NewPostgresRolloutStore(engine *database.Engine) *PostgresRolloutStore {
	return &PostgresRolloutStore{
		engine: engine,
	}
}

// CreateChannelRollout starts a channel rollout; id is generated by the caller and
// doubles as the bucketing salt. Returns 0 rows if the guarded insert was refused
// (unknown/unmapped channel or branch); a rollout already active on the channel
// surfaces as ErrResourceAlreadyExists.
func (s *PostgresRolloutStore) CreateChannelRollout(ctx context.Context, id string, appId string, channelName string, rolloutBranchName string, percentage int) (int64, error) {
	var pgID pgtype.UUID
	if err := pgID.Scan(id); err != nil {
		return 0, fmt.Errorf("failed to parse rollout id: %w", err)
	}
	rows, err := s.engine.Queries.InsertChannelRollout(ctx, pgdb.InsertChannelRolloutParams{
		ID:         pgID,
		Percentage: int32(percentage),
		AppID:      ToPgUUID(appId),
		Name:       channelName,       // c.name
		Name_2:     rolloutBranchName, // rb.name
	})
	if err != nil {
		if database.IsUniqueViolation(err) {
			return 0, &ErrResourceAlreadyExists{Resource: "channel rollout", Identifier: fmt.Sprintf("%s (appId: %s)", channelName, appId)}
		}
		return 0, fmt.Errorf("failed to create channel rollout in database: %w", err)
	}
	return rows, nil
}

// GetChannelRollout returns the active rollout summary for a channel, or nil when the
// channel has none.
func (s *PostgresRolloutStore) GetChannelRollout(ctx context.Context, appId string, channelName string) (*types.ChannelRollout, error) {
	row, err := s.engine.Queries.GetChannelRollout(ctx, pgdb.GetChannelRolloutParams{
		AppID: ToPgUUID(appId),
		Name:  channelName,
	})
	if err != nil {
		if database.IsNoRows(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to retrieve channel rollout from database: %w", err)
	}
	return &types.ChannelRollout{
		ID:                row.ID.String(),
		ChannelName:       row.ChannelName,
		DefaultBranchName: row.DefaultBranchName,
		RolloutBranchName: row.RolloutBranchName,
		Percentage:        int(row.Percentage),
		CreatedAt:         row.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:         row.UpdatedAt.Time.Format(time.RFC3339),
	}, nil
}

// UpdateChannelRolloutPercentage sets a new traffic split. Returns the number of rows
// updated: 0 means the channel had no active rollout (concurrent end).
func (s *PostgresRolloutStore) UpdateChannelRolloutPercentage(ctx context.Context, appId string, channelName string, percentage int) (int64, error) {
	return s.engine.Queries.UpdateChannelRolloutPercentage(ctx, pgdb.UpdateChannelRolloutPercentageParams{
		Percentage: int32(percentage),
		AppID:      ToPgUUID(appId),
		Name:       channelName,
	})
}

// DeleteChannelRollout ends a channel rollout by discarding it (revert outcome). Returns
// the number of rows deleted: 0 means there was no active rollout.
func (s *PostgresRolloutStore) DeleteChannelRollout(ctx context.Context, appId string, channelName string) (int64, error) {
	return s.engine.Queries.DeleteChannelRollout(ctx, pgdb.DeleteChannelRolloutParams{
		AppID: ToPgUUID(appId),
		Name:  channelName,
	})
}

// PromoteChannelRollout ends a channel rollout by promoting its rollout branch to the
// channel's mapping and discarding the rollout. Returns the number of channels repointed:
// 0 means there was no active rollout to promote.
func (s *PostgresRolloutStore) PromoteChannelRollout(ctx context.Context, appId string, channelName string) (int64, error) {
	var repointed int64
	err := s.engine.WithTx(ctx, func(q *pgdb.Queries) error {
		rows, err := q.RepointChannelToRolloutBranch(ctx, pgdb.RepointChannelToRolloutBranchParams{
			AppID: ToPgUUID(appId),
			Name:  channelName,
		})
		if err != nil {
			return err
		}
		repointed = rows
		// No active rollout: nothing to repoint or delete, commit the empty transaction.
		if rows == 0 {
			return nil
		}
		if _, err := q.DeleteChannelRollout(ctx, pgdb.DeleteChannelRolloutParams{
			AppID: ToPgUUID(appId),
			Name:  channelName,
		}); err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return 0, fmt.Errorf("failed to promote channel rollout: %w", err)
	}
	return repointed, nil
}

// GetChannelRolloutsByBranch returns the names of the channels whose active rollout
// serves the given branch. Used by the branch-delete guard to build a friendly error;
// the FK RESTRICT already blocks the delete itself.
func (s *PostgresRolloutStore) GetChannelRolloutsByBranch(ctx context.Context, appId string, branchName string) ([]string, error) {
	return s.engine.Queries.GetChannelRolloutsByBranch(ctx, pgdb.GetChannelRolloutsByBranchParams{
		AppID: ToPgUUID(appId),
		Name:  branchName,
	})
}

// GetActiveRolloutUpdates returns the active per-update rollout rows for (branch, rtv),
// one per platform.
func (s *PostgresRolloutStore) GetActiveRolloutUpdates(ctx context.Context, appId string, branchName string, runtimeVersion string) ([]types.RolloutUpdate, error) {
	rows, err := s.engine.Queries.GetActiveRolloutUpdates(ctx, pgdb.GetActiveRolloutUpdatesParams{
		AppID:   ToPgUUID(appId),
		Name:    branchName,
		Version: runtimeVersion,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve active rollout updates from database: %w", err)
	}
	updates := make([]types.RolloutUpdate, 0, len(rows))
	for _, row := range rows {
		item := types.RolloutUpdate{
			UpdateId:  strconv.FormatInt(row.ID, 10),
			Platform:  row.Platform,
			CreatedAt: row.CreatedAt.Time.Format(time.RFC3339),
		}
		if row.RolloutPercentage != nil {
			item.Percentage = int(*row.RolloutPercentage)
		}
		if row.ControlUpdateID != nil {
			control := strconv.FormatInt(*row.ControlUpdateID, 10)
			item.ControlUpdateId = &control
		}
		updates = append(updates, item)
	}
	return updates, nil
}

// SetUpdateRolloutPercentage sets the new percentage on every active rollout row for
// (branch, rtv). Returns the number of rows updated: 0 means the rollout ended in a
// concurrent edit. Monotonic-increase and stale-tab validation belong to the service.
func (s *PostgresRolloutStore) SetUpdateRolloutPercentage(ctx context.Context, appId string, branchName string, runtimeVersion string, percentage int) (int64, error) {
	pct := int32(percentage)
	return s.engine.Queries.SetUpdateRolloutPercentage(ctx, pgdb.SetUpdateRolloutPercentageParams{
		AppID:             ToPgUUID(appId),
		Name:              branchName,
		Version:           runtimeVersion,
		RolloutPercentage: &pct,
	})
}

// ClearUpdateRollout ends the per-update rollout for (branch, rtv) by clearing the
// rollout state on every active row. Returns the number of rows cleared.
func (s *PostgresRolloutStore) ClearUpdateRollout(ctx context.Context, appId string, branchName string, runtimeVersion string) (int64, error) {
	return s.engine.Queries.ClearUpdateRollout(ctx, pgdb.ClearUpdateRolloutParams{
		AppID:   ToPgUUID(appId),
		Name:    branchName,
		Version: runtimeVersion,
	})
}
