// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: build_cache.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"xprem/internal/types"
)

const buildCacheUsage = `-- name: BuildCacheUsage :one
SELECT COALESCE(sum(size), 0)::bigint AS bytes, count(*) AS objects
FROM (
    SELECT active.size FROM build_cache_objects AS active WHERE active.app_id = $1 AND active.app_identifier_id = $2
    UNION ALL
    SELECT retired.size FROM build_cache_cleanup AS retired WHERE retired.app_id = $1 AND retired.app_identifier_id = $2
) AS retained
`

type BuildCacheUsageParams struct {
	AppID           pgtype.UUID `json:"app_id"`
	AppIdentifierID pgtype.UUID `json:"app_identifier_id"`
}

type BuildCacheUsageRow struct {
	Bytes   int64 `json:"bytes"`
	Objects int64 `json:"objects"`
}

func (q *Queries) BuildCacheUsage(ctx context.Context, arg BuildCacheUsageParams) (BuildCacheUsageRow, error) {
	row := q.db.QueryRow(ctx, buildCacheUsage, arg.AppID, arg.AppIdentifierID)
	var i BuildCacheUsageRow
	err := row.Scan(&i.Bytes, &i.Objects)
	return i, err
}

const deleteBuildCacheCleanup = `-- name: DeleteBuildCacheCleanup :exec
DELETE FROM build_cache_cleanup WHERE id = $1
`

func (q *Queries) DeleteBuildCacheCleanup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuildCacheCleanup, id)
	return err
}

const deleteBuildCacheObject = `-- name: DeleteBuildCacheObject :exec
DELETE FROM build_cache_objects WHERE app_id = $1 AND app_identifier_id = $2 AND id = $3
`

type DeleteBuildCacheObjectParams struct {
	AppID           pgtype.UUID `json:"app_id"`
	AppIdentifierID pgtype.UUID `json:"app_identifier_id"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteBuildCacheObject(ctx context.Context, arg DeleteBuildCacheObjectParams) error {
	_, err := q.db.Exec(ctx, deleteBuildCacheObject, arg.AppID, arg.AppIdentifierID, arg.ID)
	return err
}

const dueBuildCacheCleanup = `-- name: DueBuildCacheCleanup :many
SELECT id, app_id, app_identifier_id, namespace, size, due_at FROM build_cache_cleanup WHERE due_at <= now() ORDER BY due_at LIMIT 4 FOR UPDATE SKIP LOCKED
`

func (q *Queries) DueBuildCacheCleanup(ctx context.Context) ([]BuildCacheCleanup, error) {
	rows, err := q.db.Query(ctx, dueBuildCacheCleanup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildCacheCleanup
	for rows.Next() {
		var i BuildCacheCleanup
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AppIdentifierID,
			&i.Namespace,
			&i.Size,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireBuildCacheObjects = `-- name: ExpireBuildCacheObjects :execrows
DELETE FROM build_cache_objects WHERE id IN (SELECT id FROM build_cache_objects WHERE expires_at <= now() LIMIT 100 FOR UPDATE SKIP LOCKED)
`

func (q *Queries) ExpireBuildCacheObjects(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireBuildCacheObjects)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBuildCacheObject = `-- name: FindBuildCacheObject :one
SELECT id, app_id, app_identifier_id, namespace, cache_key, size, sha256, created_at, expires_at, published_at FROM build_cache_objects WHERE app_id = $1 AND app_identifier_id = $2 AND namespace = $3 AND cache_key = $4 AND published_at IS NOT NULL AND expires_at > now()
`

type FindBuildCacheObjectParams struct {
	AppID           pgtype.UUID               `json:"app_id"`
	AppIdentifierID pgtype.UUID               `json:"app_identifier_id"`
	Namespace       types.BuildCacheNamespace `json:"namespace"`
	CacheKey        string                    `json:"cache_key"`
}

func (q *Queries) FindBuildCacheObject(ctx context.Context, arg FindBuildCacheObjectParams) (BuildCacheObject, error) {
	row := q.db.QueryRow(ctx, findBuildCacheObject,
		arg.AppID,
		arg.AppIdentifierID,
		arg.Namespace,
		arg.CacheKey,
	)
	var i BuildCacheObject
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Namespace,
		&i.CacheKey,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PublishedAt,
	)
	return i, err
}

const getBuildCacheUpload = `-- name: GetBuildCacheUpload :one
SELECT id, app_id, app_identifier_id, namespace, cache_key, size, sha256, created_at, expires_at, published_at FROM build_cache_objects WHERE app_id = $1 AND app_identifier_id = $2 AND id = $3 AND expires_at > now()
`

type GetBuildCacheUploadParams struct {
	AppID           pgtype.UUID `json:"app_id"`
	AppIdentifierID pgtype.UUID `json:"app_identifier_id"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) GetBuildCacheUpload(ctx context.Context, arg GetBuildCacheUploadParams) (BuildCacheObject, error) {
	row := q.db.QueryRow(ctx, getBuildCacheUpload, arg.AppID, arg.AppIdentifierID, arg.ID)
	var i BuildCacheObject
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Namespace,
		&i.CacheKey,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PublishedAt,
	)
	return i, err
}

const insertBuildCacheObject = `-- name: InsertBuildCacheObject :one
INSERT INTO build_cache_objects (id, app_id, app_identifier_id, namespace, cache_key, size, sha256)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, app_id, app_identifier_id, namespace, cache_key, size, sha256, created_at, expires_at, published_at
`

type InsertBuildCacheObjectParams struct {
	ID              pgtype.UUID               `json:"id"`
	AppID           pgtype.UUID               `json:"app_id"`
	AppIdentifierID pgtype.UUID               `json:"app_identifier_id"`
	Namespace       types.BuildCacheNamespace `json:"namespace"`
	CacheKey        string                    `json:"cache_key"`
	Size            int64                     `json:"size"`
	Sha256          string                    `json:"sha256"`
}

func (q *Queries) InsertBuildCacheObject(ctx context.Context, arg InsertBuildCacheObjectParams) (BuildCacheObject, error) {
	row := q.db.QueryRow(ctx, insertBuildCacheObject,
		arg.ID,
		arg.AppID,
		arg.AppIdentifierID,
		arg.Namespace,
		arg.CacheKey,
		arg.Size,
		arg.Sha256,
	)
	var i BuildCacheObject
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Namespace,
		&i.CacheKey,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PublishedAt,
	)
	return i, err
}

const lockBuildCacheOwner = `-- name: LockBuildCacheOwner :one
SELECT id FROM app_identifiers WHERE app_id = $1 AND id = $2 FOR UPDATE
`

type LockBuildCacheOwnerParams struct {
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) LockBuildCacheOwner(ctx context.Context, arg LockBuildCacheOwnerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockBuildCacheOwner, arg.AppID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const publishBuildCacheObject = `-- name: PublishBuildCacheObject :one
UPDATE build_cache_objects SET published_at = now(), expires_at = now() + interval '30 days'
WHERE app_id = $1 AND app_identifier_id = $2 AND id = $3 AND expires_at > now() RETURNING id, app_id, app_identifier_id, namespace, cache_key, size, sha256, created_at, expires_at, published_at
`

type PublishBuildCacheObjectParams struct {
	AppID           pgtype.UUID `json:"app_id"`
	AppIdentifierID pgtype.UUID `json:"app_identifier_id"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) PublishBuildCacheObject(ctx context.Context, arg PublishBuildCacheObjectParams) (BuildCacheObject, error) {
	row := q.db.QueryRow(ctx, publishBuildCacheObject, arg.AppID, arg.AppIdentifierID, arg.ID)
	var i BuildCacheObject
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Namespace,
		&i.CacheKey,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PublishedAt,
	)
	return i, err
}

const removePreviousBuildCacheObject = `-- name: RemovePreviousBuildCacheObject :exec
DELETE FROM build_cache_objects WHERE app_id = $1 AND app_identifier_id = $2 AND namespace = $3 AND cache_key = $4 AND published_at IS NOT NULL AND id <> $5
`

type RemovePreviousBuildCacheObjectParams struct {
	AppID           pgtype.UUID               `json:"app_id"`
	AppIdentifierID pgtype.UUID               `json:"app_identifier_id"`
	Namespace       types.BuildCacheNamespace `json:"namespace"`
	CacheKey        string                    `json:"cache_key"`
	ID              pgtype.UUID               `json:"id"`
}

func (q *Queries) RemovePreviousBuildCacheObject(ctx context.Context, arg RemovePreviousBuildCacheObjectParams) error {
	_, err := q.db.Exec(ctx, removePreviousBuildCacheObject,
		arg.AppID,
		arg.AppIdentifierID,
		arg.Namespace,
		arg.CacheKey,
		arg.ID,
	)
	return err
}

const retryBuildCacheCleanup = `-- name: RetryBuildCacheCleanup :exec
UPDATE build_cache_cleanup SET due_at = now() + interval '15 minutes' WHERE id = $1
`

func (q *Queries) RetryBuildCacheCleanup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, retryBuildCacheCleanup, id)
	return err
}
