// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"xprem/internal/types"
)

const countBuilds = `-- name: CountBuilds :one
SELECT count(*) FROM builds WHERE app_id=$1
`

func (q *Queries) CountBuilds(ctx context.Context, appID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBuilds, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deferBuildArtifactCleanup = `-- name: DeferBuildArtifactCleanup :exec
UPDATE build_artifact_cleanup SET attempts = attempts + 1, last_error = $1, due_at = now() + $2::interval
WHERE id = $3
`

type DeferBuildArtifactCleanupParams struct {
	LastError *string         `json:"last_error"`
	Backoff   pgtype.Interval `json:"backoff"`
	ID        int64           `json:"id"`
}

func (q *Queries) DeferBuildArtifactCleanup(ctx context.Context, arg DeferBuildArtifactCleanupParams) error {
	_, err := q.db.Exec(ctx, deferBuildArtifactCleanup, arg.LastError, arg.Backoff, arg.ID)
	return err
}

const deleteBuildArtifactCleanup = `-- name: DeleteBuildArtifactCleanup :exec
DELETE FROM build_artifact_cleanup WHERE id = $1
`

func (q *Queries) DeleteBuildArtifactCleanup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBuildArtifactCleanup, id)
	return err
}

const failStaleBuilds = `-- name: FailStaleBuilds :execrows
UPDATE builds SET status = 'failed', finished_at = now(),
    duration_ms = GREATEST((EXTRACT(EPOCH FROM now() - started_at) * 1000)::bigint, 0), updated_at = now()
WHERE status IN ('building', 'uploading') AND updated_at < now() - $1::interval
`

func (q *Queries) FailStaleBuilds(ctx context.Context, staleAfter pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleBuilds, staleAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBuild = `-- name: GetBuild :one
SELECT id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at FROM builds WHERE app_id=$1 AND id=$2
`

type GetBuildParams struct {
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetBuild(ctx context.Context, arg GetBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, getBuild, arg.AppID, arg.ID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Platform,
		&i.ApplicationID,
		&i.Status,
		&i.ArtifactType,
		&i.Size,
		&i.Sha256,
		&i.ArtifactKey,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplay,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const insertBuild = `-- name: InsertBuild :one
INSERT INTO builds(id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
ON CONFLICT (id) DO NOTHING RETURNING id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at
`

type InsertBuildParams struct {
	ID              pgtype.UUID             `json:"id"`
	AppID           pgtype.UUID             `json:"app_id"`
	AppIdentifierID pgtype.UUID             `json:"app_identifier_id"`
	Platform        types.Platform          `json:"platform"`
	ApplicationID   string                  `json:"application_id"`
	Status          types.BuildStatus       `json:"status"`
	ArtifactType    types.BuildArtifactType `json:"artifact_type"`
	Size            int64                   `json:"size"`
	Sha256          string                  `json:"sha256"`
	ArtifactKey     string                  `json:"artifact_key"`
	Metadata        []byte                  `json:"metadata"`
	ActorType       string                  `json:"actor_type"`
	ActorID         string                  `json:"actor_id"`
	ActorDisplay    string                  `json:"actor_display"`
	StartedAt       pgtype.Timestamptz      `json:"started_at"`
	FinishedAt      pgtype.Timestamptz      `json:"finished_at"`
	DurationMs      *int64                  `json:"duration_ms"`
}

func (q *Queries) InsertBuild(ctx context.Context, arg InsertBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, insertBuild,
		arg.ID,
		arg.AppID,
		arg.AppIdentifierID,
		arg.Platform,
		arg.ApplicationID,
		arg.Status,
		arg.ArtifactType,
		arg.Size,
		arg.Sha256,
		arg.ArtifactKey,
		arg.Metadata,
		arg.ActorType,
		arg.ActorID,
		arg.ActorDisplay,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Platform,
		&i.ApplicationID,
		&i.Status,
		&i.ArtifactType,
		&i.Size,
		&i.Sha256,
		&i.ArtifactKey,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplay,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const insertBuildShare = `-- name: InsertBuildShare :one
INSERT INTO build_shares(id,build_id,token_hash,expires_at) VALUES ($1,$2,$3,$4) RETURNING id, build_id, token_hash, created_at, expires_at, revoked_at
`

type InsertBuildShareParams struct {
	ID        pgtype.UUID        `json:"id"`
	BuildID   pgtype.UUID        `json:"build_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertBuildShare(ctx context.Context, arg InsertBuildShareParams) (BuildShare, error) {
	row := q.db.QueryRow(ctx, insertBuildShare,
		arg.ID,
		arg.BuildID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i BuildShare
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listBuildShares = `-- name: ListBuildShares :many
SELECT id, build_id, token_hash, created_at, expires_at, revoked_at FROM build_shares WHERE build_id=$1 ORDER BY created_at DESC
`

func (q *Queries) ListBuildShares(ctx context.Context, buildID pgtype.UUID) ([]BuildShare, error) {
	rows, err := q.db.Query(ctx, listBuildShares, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildShare
	for rows.Next() {
		var i BuildShare
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuilds = `-- name: ListBuilds :many
SELECT id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at FROM builds
WHERE app_id=$1
  AND ($4::timestamptz IS NULL
       OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC,id DESC LIMIT $2 OFFSET $3
`

type ListBuildsParams struct {
	AppID           pgtype.UUID        `json:"app_id"`
	Limit           int32              `json:"limit"`
	Offset          int32              `json:"offset"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
}

func (q *Queries) ListBuilds(ctx context.Context, arg ListBuildsParams) ([]Build, error) {
	rows, err := q.db.Query(ctx, listBuilds,
		arg.AppID,
		arg.Limit,
		arg.Offset,
		arg.BeforeCreatedAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AppIdentifierID,
			&i.Platform,
			&i.ApplicationID,
			&i.Status,
			&i.ArtifactType,
			&i.Size,
			&i.Sha256,
			&i.ArtifactKey,
			&i.Metadata,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplay,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueBuildArtifactCleanup = `-- name: ListDueBuildArtifactCleanup :many
SELECT id, app_identifier_id, build_id, artifact_type, attempts
FROM build_artifact_cleanup WHERE due_at <= now()
ORDER BY due_at, id LIMIT $1 FOR UPDATE SKIP LOCKED
`

type ListDueBuildArtifactCleanupRow struct {
	ID              int64                   `json:"id"`
	AppIdentifierID pgtype.UUID             `json:"app_identifier_id"`
	BuildID         pgtype.UUID             `json:"build_id"`
	ArtifactType    types.BuildArtifactType `json:"artifact_type"`
	Attempts        int32                   `json:"attempts"`
}

func (q *Queries) ListDueBuildArtifactCleanup(ctx context.Context, batchSize int32) ([]ListDueBuildArtifactCleanupRow, error) {
	rows, err := q.db.Query(ctx, listDueBuildArtifactCleanup, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueBuildArtifactCleanupRow
	for rows.Next() {
		var i ListDueBuildArtifactCleanupRow
		if err := rows.Scan(
			&i.ID,
			&i.AppIdentifierID,
			&i.BuildID,
			&i.ArtifactType,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleBuildStaging = `-- name: ListStaleBuildStaging :many
SELECT b.id, b.app_identifier_id, b.artifact_type
FROM builds b LEFT JOIN build_staging_sweeps s ON s.build_id = b.id
WHERE b.updated_at < now() - $1::interval
  AND b.status IN ('ready', 'failed', 'uploading')
  AND (s.build_id IS NULL OR (b.status <> 'ready' AND s.swept_at < b.updated_at))
ORDER BY b.created_at, b.id LIMIT $2 FOR UPDATE OF b SKIP LOCKED
`

type ListStaleBuildStagingParams struct {
	StaleAfter pgtype.Interval `json:"stale_after"`
	BatchSize  int32           `json:"batch_size"`
}

type ListStaleBuildStagingRow struct {
	ID              pgtype.UUID             `json:"id"`
	AppIdentifierID pgtype.UUID             `json:"app_identifier_id"`
	ArtifactType    types.BuildArtifactType `json:"artifact_type"`
}

func (q *Queries) ListStaleBuildStaging(ctx context.Context, arg ListStaleBuildStagingParams) ([]ListStaleBuildStagingRow, error) {
	rows, err := q.db.Query(ctx, listStaleBuildStaging, arg.StaleAfter, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleBuildStagingRow
	for rows.Next() {
		var i ListStaleBuildStagingRow
		if err := rows.Scan(&i.ID, &i.AppIdentifierID, &i.ArtifactType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBuild = `-- name: LockBuild :one
SELECT id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at FROM builds WHERE app_id=$1 AND id=$2 FOR UPDATE
`

type LockBuildParams struct {
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) LockBuild(ctx context.Context, arg LockBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, lockBuild, arg.AppID, arg.ID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Platform,
		&i.ApplicationID,
		&i.Status,
		&i.ArtifactType,
		&i.Size,
		&i.Sha256,
		&i.ArtifactKey,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplay,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const markBuildStagingSwept = `-- name: MarkBuildStagingSwept :exec
INSERT INTO build_staging_sweeps (build_id, swept_at) VALUES ($1, now())
ON CONFLICT (build_id) DO UPDATE SET swept_at = now()
`

func (q *Queries) MarkBuildStagingSwept(ctx context.Context, buildID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markBuildStagingSwept, buildID)
	return err
}

const resolveBuildShare = `-- name: ResolveBuildShare :one
SELECT b.id, b.app_id, s.expires_at AS share_expires_at FROM build_shares s JOIN builds b ON b.id=s.build_id
WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND b.status='ready' AND b.artifact_type IN ('apk', 'ipa')
`

type ResolveBuildShareRow struct {
	ID             pgtype.UUID        `json:"id"`
	AppID          pgtype.UUID        `json:"app_id"`
	ShareExpiresAt pgtype.Timestamptz `json:"share_expires_at"`
}

func (q *Queries) ResolveBuildShare(ctx context.Context, tokenHash string) (ResolveBuildShareRow, error) {
	row := q.db.QueryRow(ctx, resolveBuildShare, tokenHash)
	var i ResolveBuildShareRow
	err := row.Scan(&i.ID, &i.AppID, &i.ShareExpiresAt)
	return i, err
}

const revokeBuildShare = `-- name: RevokeBuildShare :execrows
UPDATE build_shares SET revoked_at=COALESCE(revoked_at,now()) WHERE build_id=$1 AND id=$2
`

type RevokeBuildShareParams struct {
	BuildID pgtype.UUID `json:"build_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeBuildShare(ctx context.Context, arg RevokeBuildShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeBuildShare, arg.BuildID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBuild = `-- name: UpdateBuild :one
UPDATE builds SET status=$3, size=$4, sha256=$5, metadata=$6, finished_at=$7, duration_ms=$8,
    ready_at=CASE WHEN $3='ready' THEN COALESCE(ready_at, now()) ELSE NULL END, updated_at=now()
WHERE app_id=$1 AND id=$2 RETURNING id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at
`

type UpdateBuildParams struct {
	AppID      pgtype.UUID        `json:"app_id"`
	ID         pgtype.UUID        `json:"id"`
	Status     types.BuildStatus  `json:"status"`
	Size       int64              `json:"size"`
	Sha256     string             `json:"sha256"`
	Metadata   []byte             `json:"metadata"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs *int64             `json:"duration_ms"`
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, updateBuild,
		arg.AppID,
		arg.ID,
		arg.Status,
		arg.Size,
		arg.Sha256,
		arg.Metadata,
		arg.FinishedAt,
		arg.DurationMs,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Platform,
		&i.ApplicationID,
		&i.Status,
		&i.ArtifactType,
		&i.Size,
		&i.Sha256,
		&i.ArtifactKey,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplay,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}
