// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ios_devices.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"xprem/internal/auditlog"
	"xprem/internal/types"
)

const claimIosDeviceInvitation = `-- name: ClaimIosDeviceInvitation :execrows
UPDATE ios_device_invitations SET claimed_at = now(), claim_token = $2
WHERE id = $1 AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at > now()
    AND (claimed_at IS NULL OR claimed_at < now() - interval '5 minutes')
`

type ClaimIosDeviceInvitationParams struct {
	ID         pgtype.UUID `json:"id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

// A claim older than five minutes may be reclaimed; its old owner can no longer finish or release it.
func (q *Queries) ClaimIosDeviceInvitation(ctx context.Context, arg ClaimIosDeviceInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIosDeviceInvitation, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeIosDeviceInvitation = `-- name: ConsumeIosDeviceInvitation :execrows
UPDATE ios_device_invitations SET consumed_at = now(), registration_id = $2, claimed_at = NULL, claim_token = NULL
WHERE id = $1 AND claim_token = $3 AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

type ConsumeIosDeviceInvitationParams struct {
	ID             pgtype.UUID `json:"id"`
	RegistrationID pgtype.UUID `json:"registration_id"`
	ClaimToken     pgtype.UUID `json:"claim_token"`
}

func (q *Queries) ConsumeIosDeviceInvitation(ctx context.Context, arg ConsumeIosDeviceInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeIosDeviceInvitation, arg.ID, arg.RegistrationID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIosDeviceRegistration = `-- name: GetIosDeviceRegistration :one
SELECT r.status, r.device_name, r.product, r.error
FROM ios_device_registrations r
JOIN ios_device_invitations i ON i.id = r.invitation_id
WHERE i.token_hash = $1 AND r.id = $2
`

type GetIosDeviceRegistrationParams struct {
	TokenHash string      `json:"token_hash"`
	ID        pgtype.UUID `json:"id"`
}

type GetIosDeviceRegistrationRow struct {
	Status     types.IosDeviceRegistrationStatus `json:"status"`
	DeviceName string                            `json:"device_name"`
	Product    string                            `json:"product"`
	Error      *string                           `json:"error"`
}

func (q *Queries) GetIosDeviceRegistration(ctx context.Context, arg GetIosDeviceRegistrationParams) (GetIosDeviceRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getIosDeviceRegistration, arg.TokenHash, arg.ID)
	var i GetIosDeviceRegistrationRow
	err := row.Scan(
		&i.Status,
		&i.DeviceName,
		&i.Product,
		&i.Error,
	)
	return i, err
}

const insertIosDeviceInvitation = `-- name: InsertIosDeviceInvitation :one
INSERT INTO ios_device_invitations (
    id, app_id, token_hash, challenge, label, expires_at,
    created_by_actor_type, created_by_actor_id, created_by_actor_display
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING created_at
`

type InsertIosDeviceInvitationParams struct {
	ID                    pgtype.UUID        `json:"id"`
	AppID                 pgtype.UUID        `json:"app_id"`
	TokenHash             string             `json:"token_hash"`
	Challenge             string             `json:"challenge"`
	Label                 string             `json:"label"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	CreatedByActorType    auditlog.ActorType `json:"created_by_actor_type"`
	CreatedByActorID      string             `json:"created_by_actor_id"`
	CreatedByActorDisplay string             `json:"created_by_actor_display"`
}

func (q *Queries) InsertIosDeviceInvitation(ctx context.Context, arg InsertIosDeviceInvitationParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertIosDeviceInvitation,
		arg.ID,
		arg.AppID,
		arg.TokenHash,
		arg.Challenge,
		arg.Label,
		arg.ExpiresAt,
		arg.CreatedByActorType,
		arg.CreatedByActorID,
		arg.CreatedByActorDisplay,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertIosDeviceRegistration = `-- name: InsertIosDeviceRegistration :exec
INSERT INTO ios_device_registrations (
    id, invitation_id, udid, device_name, product, os_version, status, apple_device_id, error
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertIosDeviceRegistrationParams struct {
	ID            pgtype.UUID                       `json:"id"`
	InvitationID  pgtype.UUID                       `json:"invitation_id"`
	Udid          string                            `json:"udid"`
	DeviceName    string                            `json:"device_name"`
	Product       string                            `json:"product"`
	OsVersion     string                            `json:"os_version"`
	Status        types.IosDeviceRegistrationStatus `json:"status"`
	AppleDeviceID *string                           `json:"apple_device_id"`
	Error         *string                           `json:"error"`
}

func (q *Queries) InsertIosDeviceRegistration(ctx context.Context, arg InsertIosDeviceRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertIosDeviceRegistration,
		arg.ID,
		arg.InvitationID,
		arg.Udid,
		arg.DeviceName,
		arg.Product,
		arg.OsVersion,
		arg.Status,
		arg.AppleDeviceID,
		arg.Error,
	)
	return err
}

const listIosDeviceInvitations = `-- name: ListIosDeviceInvitations :many
SELECT i.id, i.label, i.expires_at, i.revoked_at, i.consumed_at, i.created_at, i.created_by_actor_display,
       COALESCE(r.device_name, '')::text AS device_name, COALESCE(r.product, '')::text AS device_product
FROM ios_device_invitations i
LEFT JOIN ios_device_registrations r ON r.id = i.registration_id
WHERE i.app_id = $1
ORDER BY i.created_at DESC, i.id
`

type ListIosDeviceInvitationsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Label                 string             `json:"label"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	ConsumedAt            pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	CreatedByActorDisplay string             `json:"created_by_actor_display"`
	DeviceName            string             `json:"device_name"`
	DeviceProduct         string             `json:"device_product"`
}

func (q *Queries) ListIosDeviceInvitations(ctx context.Context, appID pgtype.UUID) ([]ListIosDeviceInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listIosDeviceInvitations, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIosDeviceInvitationsRow
	for rows.Next() {
		var i ListIosDeviceInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ConsumedAt,
			&i.CreatedAt,
			&i.CreatedByActorDisplay,
			&i.DeviceName,
			&i.DeviceProduct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegisteredIosDevices = `-- name: ListRegisteredIosDevices :many
SELECT DISTINCT ON (upper(r.udid)) upper(r.udid)::text AS udid, r.product, r.os_version, r.created_at,
       i.id AS invitation_id, i.label
FROM ios_device_registrations r
JOIN ios_device_invitations i ON i.id = r.invitation_id
WHERE i.app_id = $1 AND r.status = 'registered'
ORDER BY upper(r.udid), r.created_at DESC
`

type ListRegisteredIosDevicesRow struct {
	Udid         string             `json:"udid"`
	Product      string             `json:"product"`
	OsVersion    string             `json:"os_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	InvitationID pgtype.UUID        `json:"invitation_id"`
	Label        string             `json:"label"`
}

func (q *Queries) ListRegisteredIosDevices(ctx context.Context, appID pgtype.UUID) ([]ListRegisteredIosDevicesRow, error) {
	rows, err := q.db.Query(ctx, listRegisteredIosDevices, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegisteredIosDevicesRow
	for rows.Next() {
		var i ListRegisteredIosDevicesRow
		if err := rows.Scan(
			&i.Udid,
			&i.Product,
			&i.OsVersion,
			&i.CreatedAt,
			&i.InvitationID,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseIosDeviceInvitation = `-- name: ReleaseIosDeviceInvitation :execrows
UPDATE ios_device_invitations SET claimed_at = NULL, claim_token = NULL
WHERE id = $1 AND claim_token = $2
`

type ReleaseIosDeviceInvitationParams struct {
	ID         pgtype.UUID `json:"id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) ReleaseIosDeviceInvitation(ctx context.Context, arg ReleaseIosDeviceInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIosDeviceInvitation, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveIosDeviceInvitation = `-- name: ResolveIosDeviceInvitation :one
SELECT i.id, i.app_id, i.challenge, i.label, i.expires_at, (i.consumed_at IS NOT NULL)::bool AS consumed, a.name AS app_name
FROM ios_device_invitations i
JOIN apps a ON a.id = i.app_id
WHERE i.token_hash = $1 AND i.revoked_at IS NULL AND i.expires_at > now()
`

type ResolveIosDeviceInvitationRow struct {
	ID        pgtype.UUID        `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Challenge string             `json:"challenge"`
	Label     string             `json:"label"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Consumed  bool               `json:"consumed"`
	AppName   string             `json:"app_name"`
}

func (q *Queries) ResolveIosDeviceInvitation(ctx context.Context, tokenHash string) (ResolveIosDeviceInvitationRow, error) {
	row := q.db.QueryRow(ctx, resolveIosDeviceInvitation, tokenHash)
	var i ResolveIosDeviceInvitationRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Challenge,
		&i.Label,
		&i.ExpiresAt,
		&i.Consumed,
		&i.AppName,
	)
	return i, err
}

const revokeIosDeviceInvitation = `-- name: RevokeIosDeviceInvitation :one
UPDATE ios_device_invitations SET revoked_at = COALESCE(revoked_at, now())
WHERE app_id = $1 AND id = $2
RETURNING label
`

type RevokeIosDeviceInvitationParams struct {
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeIosDeviceInvitation(ctx context.Context, arg RevokeIosDeviceInvitationParams) (string, error) {
	row := q.db.QueryRow(ctx, revokeIosDeviceInvitation, arg.AppID, arg.ID)
	var label string
	err := row.Scan(&label)
	return label, err
}
