// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ios_credentials.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"xprem/internal/types"
)

const deleteAppStoreConnectApiKey = `-- name: DeleteAppStoreConnectApiKey :execresult
DELETE FROM app_store_connect_api_keys WHERE app_id = $1
`

func (q *Queries) DeleteAppStoreConnectApiKey(ctx context.Context, appID pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteAppStoreConnectApiKey, appID)
}

const getAppStoreConnectApiKey = `-- name: GetAppStoreConnectApiKey :one
SELECT key_id, issuer_id, sealed_private_key, created_at, updated_at
FROM app_store_connect_api_keys
WHERE app_id = $1
`

type GetAppStoreConnectApiKeyRow struct {
	KeyID            string             `json:"key_id"`
	IssuerID         string             `json:"issuer_id"`
	SealedPrivateKey string             `json:"sealed_private_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAppStoreConnectApiKey(ctx context.Context, appID pgtype.UUID) (GetAppStoreConnectApiKeyRow, error) {
	row := q.db.QueryRow(ctx, getAppStoreConnectApiKey, appID)
	var i GetAppStoreConnectApiKeyRow
	err := row.Scan(
		&i.KeyID,
		&i.IssuerID,
		&i.SealedPrivateKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIosCertificate = `-- name: GetIosCertificate :one
SELECT id, common_name, serial_number, fingerprint_sha1, certificate_type, team_id,
       expires_at, source, created_at
FROM ios_certificates
WHERE id = $1
`

type GetIosCertificateRow struct {
	ID              pgtype.UUID                `json:"id"`
	CommonName      string                     `json:"common_name"`
	SerialNumber    string                     `json:"serial_number"`
	FingerprintSha1 string                     `json:"fingerprint_sha1"`
	CertificateType types.IosCertificateType   `json:"certificate_type"`
	TeamID          string                     `json:"team_id"`
	ExpiresAt       pgtype.Timestamptz         `json:"expires_at"`
	Source          types.IosCertificateSource `json:"source"`
	CreatedAt       pgtype.Timestamptz         `json:"created_at"`
}

func (q *Queries) GetIosCertificate(ctx context.Context, id pgtype.UUID) (GetIosCertificateRow, error) {
	row := q.db.QueryRow(ctx, getIosCertificate, id)
	var i GetIosCertificateRow
	err := row.Scan(
		&i.ID,
		&i.CommonName,
		&i.SerialNumber,
		&i.FingerprintSha1,
		&i.CertificateType,
		&i.TeamID,
		&i.ExpiresAt,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getIosSigningSetting = `-- name: GetIosSigningSetting :one
SELECT mode, certificate_id
FROM ios_signing_settings
WHERE app_identifier_id = $1
`

type GetIosSigningSettingRow struct {
	Mode          types.IosSigningMode `json:"mode"`
	CertificateID pgtype.UUID          `json:"certificate_id"`
}

func (q *Queries) GetIosSigningSetting(ctx context.Context, appIdentifierID pgtype.UUID) (GetIosSigningSettingRow, error) {
	row := q.db.QueryRow(ctx, getIosSigningSetting, appIdentifierID)
	var i GetIosSigningSettingRow
	err := row.Scan(&i.Mode, &i.CertificateID)
	return i, err
}

const insertIosCertificate = `-- name: InsertIosCertificate :one
INSERT INTO ios_certificates (
    id, sealed_certificate, sealed_certificate_password, common_name, serial_number,
    fingerprint_sha1, certificate_type, team_id, expires_at, source
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (fingerprint_sha1) DO UPDATE SET fingerprint_sha1 = EXCLUDED.fingerprint_sha1
RETURNING id
`

type InsertIosCertificateParams struct {
	ID                        pgtype.UUID                `json:"id"`
	SealedCertificate         string                     `json:"sealed_certificate"`
	SealedCertificatePassword string                     `json:"sealed_certificate_password"`
	CommonName                string                     `json:"common_name"`
	SerialNumber              string                     `json:"serial_number"`
	FingerprintSha1           string                     `json:"fingerprint_sha1"`
	CertificateType           types.IosCertificateType   `json:"certificate_type"`
	TeamID                    string                     `json:"team_id"`
	ExpiresAt                 pgtype.Timestamptz         `json:"expires_at"`
	Source                    types.IosCertificateSource `json:"source"`
}

// DO UPDATE instead of DO NOTHING so RETURNING yields the id of an existing row.
func (q *Queries) InsertIosCertificate(ctx context.Context, arg InsertIosCertificateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertIosCertificate,
		arg.ID,
		arg.SealedCertificate,
		arg.SealedCertificatePassword,
		arg.CommonName,
		arg.SerialNumber,
		arg.FingerprintSha1,
		arg.CertificateType,
		arg.TeamID,
		arg.ExpiresAt,
		arg.Source,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listIosCertificates = `-- name: ListIosCertificates :many
SELECT id, common_name, serial_number, fingerprint_sha1, certificate_type, team_id,
       expires_at, source, created_at
FROM ios_certificates
ORDER BY created_at DESC, id
`

type ListIosCertificatesRow struct {
	ID              pgtype.UUID                `json:"id"`
	CommonName      string                     `json:"common_name"`
	SerialNumber    string                     `json:"serial_number"`
	FingerprintSha1 string                     `json:"fingerprint_sha1"`
	CertificateType types.IosCertificateType   `json:"certificate_type"`
	TeamID          string                     `json:"team_id"`
	ExpiresAt       pgtype.Timestamptz         `json:"expires_at"`
	Source          types.IosCertificateSource `json:"source"`
	CreatedAt       pgtype.Timestamptz         `json:"created_at"`
}

func (q *Queries) ListIosCertificates(ctx context.Context) ([]ListIosCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listIosCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIosCertificatesRow
	for rows.Next() {
		var i ListIosCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CommonName,
			&i.SerialNumber,
			&i.FingerprintSha1,
			&i.CertificateType,
			&i.TeamID,
			&i.ExpiresAt,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIosCertificateFile = `-- name: UpdateIosCertificateFile :exec
UPDATE ios_certificates
SET sealed_certificate = $2, sealed_certificate_password = $3, updated_at = now()
WHERE id = $1
`

type UpdateIosCertificateFileParams struct {
	ID                        pgtype.UUID `json:"id"`
	SealedCertificate         string      `json:"sealed_certificate"`
	SealedCertificatePassword string      `json:"sealed_certificate_password"`
}

func (q *Queries) UpdateIosCertificateFile(ctx context.Context, arg UpdateIosCertificateFileParams) error {
	_, err := q.db.Exec(ctx, updateIosCertificateFile, arg.ID, arg.SealedCertificate, arg.SealedCertificatePassword)
	return err
}

const upsertAppStoreConnectApiKey = `-- name: UpsertAppStoreConnectApiKey :exec
INSERT INTO app_store_connect_api_keys (id, app_id, key_id, issuer_id, sealed_private_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (app_id) DO UPDATE SET
    key_id = EXCLUDED.key_id,
    issuer_id = EXCLUDED.issuer_id,
    sealed_private_key = EXCLUDED.sealed_private_key,
    updated_at = now()
`

type UpsertAppStoreConnectApiKeyParams struct {
	ID               pgtype.UUID `json:"id"`
	AppID            pgtype.UUID `json:"app_id"`
	KeyID            string      `json:"key_id"`
	IssuerID         string      `json:"issuer_id"`
	SealedPrivateKey string      `json:"sealed_private_key"`
}

func (q *Queries) UpsertAppStoreConnectApiKey(ctx context.Context, arg UpsertAppStoreConnectApiKeyParams) error {
	_, err := q.db.Exec(ctx, upsertAppStoreConnectApiKey,
		arg.ID,
		arg.AppID,
		arg.KeyID,
		arg.IssuerID,
		arg.SealedPrivateKey,
	)
	return err
}

const upsertIosSigningSetting = `-- name: UpsertIosSigningSetting :exec
INSERT INTO ios_signing_settings (app_identifier_id, mode, certificate_id)
VALUES ($1, $2, $3)
ON CONFLICT (app_identifier_id) DO UPDATE SET
    mode = EXCLUDED.mode,
    certificate_id = EXCLUDED.certificate_id,
    updated_at = now()
`

type UpsertIosSigningSettingParams struct {
	AppIdentifierID pgtype.UUID          `json:"app_identifier_id"`
	Mode            types.IosSigningMode `json:"mode"`
	CertificateID   pgtype.UUID          `json:"certificate_id"`
}

func (q *Queries) UpsertIosSigningSetting(ctx context.Context, arg UpsertIosSigningSettingParams) error {
	_, err := q.db.Exec(ctx, upsertIosSigningSetting, arg.AppIdentifierID, arg.Mode, arg.CertificateID)
	return err
}
