// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"xprem/internal/types"
)

type ApiKey struct {
	ID         int64              `json:"id"`
	AppID      pgtype.UUID        `json:"app_id"`
	Name       string             `json:"name"`
	Hint       string             `json:"hint"`
	HashedKey  string             `json:"hashed_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	AllowedIps []netip.Prefix     `json:"allowed_ips"`
}

type ApiKeyBranchRule struct {
	ID        int64              `json:"id"`
	ApiKeyID  int64              `json:"api_key_id"`
	Pattern   string             `json:"pattern"`
	Actions   []string           `json:"actions"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type App struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	KeysMode           *string            `json:"keys_mode"`
	SealedPublicKey    *string            `json:"sealed_public_key"`
	SealedPrivateKey   *string            `json:"sealed_private_key"`
	PathPublicKey      *string            `json:"path_public_key"`
	PathPrivateKey     *string            `json:"path_private_key"`
	AwsSecretIDPublic  *string            `json:"aws_secret_id_public"`
	AwsSecretIDPrivate *string            `json:"aws_secret_id_private"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AuditExportState struct {
	ID             bool  `json:"id"`
	LastExportedID int64 `json:"last_exported_id"`
}

type AuditLogEvent struct {
	ID            int64              `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ActorType     string             `json:"actor_type"`
	ActorID       string             `json:"actor_id"`
	ActorDisplay  string             `json:"actor_display"`
	Action        string             `json:"action"`
	TargetType    string             `json:"target_type"`
	TargetID      string             `json:"target_id"`
	TargetDisplay string             `json:"target_display"`
	AppID         *string            `json:"app_id"`
	Outcome       string             `json:"outcome"`
	Ip            string             `json:"ip"`
	UserAgent     string             `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
}

type Blob struct {
	AppID       pgtype.UUID        `json:"app_id"`
	Hash        string             `json:"hash"`
	Size        int64              `json:"size"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Branch struct {
	ID        int64              `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Protected bool               `json:"protected"`
}

type Channel struct {
	ID                   int64              `json:"id"`
	AppID                pgtype.UUID        `json:"app_id"`
	BranchID             *int64             `json:"branch_id"`
	Name                 string             `json:"name"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	BranchSurfingEnabled bool               `json:"branch_surfing_enabled"`
	BranchSurfingPattern string             `json:"branch_surfing_pattern"`
}

type ChannelRollout struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       int64              `json:"channel_id"`
	RolloutBranchID int64              `json:"rollout_branch_id"`
	Percentage      int32              `json:"percentage"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DeviceHealthOutbox struct {
	ID               int64              `json:"id"`
	EventType        string             `json:"event_type"`
	AppID            pgtype.UUID        `json:"app_id"`
	EasClientID      pgtype.UUID        `json:"eas_client_id"`
	UpdateID         pgtype.UUID        `json:"update_id"`
	PreviousUpdateID pgtype.UUID        `json:"previous_update_id"`
	FailureType      *string            `json:"failure_type"`
	FatalError       string             `json:"fatal_error"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
}

type DeviceIdentity struct {
	AppID                   pgtype.UUID        `json:"app_id"`
	EasClientID             pgtype.UUID        `json:"eas_client_id"`
	Metadata                []byte             `json:"metadata"`
	CountryCode             *string            `json:"country_code"`
	City                    *string            `json:"city"`
	Lat                     *float64           `json:"lat"`
	Lng                     *float64           `json:"lng"`
	FirstSeenAt             pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	CurrentUpdateID         pgtype.UUID        `json:"current_update_id"`
	DeviceModel             *string            `json:"device_model"`
	OsName                  *string            `json:"os_name"`
	OsVersion               *string            `json:"os_version"`
	BranchName              *string            `json:"branch_name"`
	RuntimeVersion          *string            `json:"runtime_version"`
	Platform                *string            `json:"platform"`
	PublishGroup            pgtype.UUID        `json:"publish_group"`
	AppVersion              *string            `json:"app_version"`
	CurrentUpdateObservedAt pgtype.Timestamptz `json:"current_update_observed_at"`
	CurrentUpdateArrivedAt  pgtype.Timestamptz `json:"current_update_arrived_at"`
}

type DeviceUpdateFailure struct {
	AppID       pgtype.UUID        `json:"app_id"`
	EasClientID pgtype.UUID        `json:"eas_client_id"`
	UpdateID    pgtype.UUID        `json:"update_id"`
	FailureType string             `json:"failure_type"`
	FatalError  string             `json:"fatal_error"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
}

type DeviceUpdateRuntimeState struct {
	AppID         pgtype.UUID        `json:"app_id"`
	EasClientID   pgtype.UUID        `json:"eas_client_id"`
	UpdateID      pgtype.UUID        `json:"update_id"`
	LastStartedAt pgtype.Timestamptz `json:"last_started_at"`
	LastCrashedAt pgtype.Timestamptz `json:"last_crashed_at"`
}

type EnterpriseLicense struct {
	Singleton              bool               `json:"singleton"`
	LicenseKey             string             `json:"license_key"`
	SealedActivationSecret string             `json:"sealed_activation_secret"`
	OrgName                string             `json:"org_name"`
	PlanCode               string             `json:"plan_code"`
	SubscriptionStartAt    pgtype.Timestamptz `json:"subscription_start_at"`
	SubscriptionEndAt      pgtype.Timestamptz `json:"subscription_end_at"`
	SubscriptionRenewalAt  pgtype.Timestamptz `json:"subscription_renewal_at"`
	ActivatedAt            pgtype.Timestamptz `json:"activated_at"`
	LastValidatedAt        pgtype.Timestamptz `json:"last_validated_at"`
	ValidationFailedAt     pgtype.Timestamptz `json:"validation_failed_at"`
	ValidationErrorCode    *string            `json:"validation_error_code"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type IdentitySchema struct {
	AppID     pgtype.UUID        `json:"app_id"`
	Key       string             `json:"key"`
	ValueType string             `json:"value_type"`
	MaxLength int32              `json:"max_length"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdentityValueStat struct {
	AppID       pgtype.UUID        `json:"app_id"`
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	DeviceCount int64              `json:"device_count"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type OauthAuthorizationCode struct {
	ID            pgtype.UUID        `json:"id"`
	ClientID      pgtype.UUID        `json:"client_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	Scope         string             `json:"scope"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
}

type OauthClient struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	RedirectUris []string           `json:"redirect_uris"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Permissions []string           `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RuntimeVersion struct {
	ID        int64              `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Version   string             `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ServerInstance struct {
	Singleton bool               `json:"singleton"`
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SsoConfig struct {
	Singleton            bool               `json:"singleton"`
	Issuer               string             `json:"issuer"`
	ClientID             string             `json:"client_id"`
	SealedClientSecret   string             `json:"sealed_client_secret"`
	ProviderName         string             `json:"provider_name"`
	Scopes               string             `json:"scopes"`
	Enabled              bool               `json:"enabled"`
	AllowedEmailDomains  []string           `json:"allowed_email_domains"`
	AllowedGroups        []string           `json:"allowed_groups"`
	GroupsClaim          string             `json:"groups_claim"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	TrustUnverifiedEmail bool               `json:"trust_unverified_email"`
	ManualUserValidation bool               `json:"manual_user_validation"`
}

type SsoIdentity struct {
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       string             `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type Update struct {
	ID                int64                     `json:"id"`
	UpdateUuid        pgtype.UUID               `json:"update_uuid"`
	BranchID          int64                     `json:"branch_id"`
	RuntimeVersionID  int64                     `json:"runtime_version_id"`
	UpdateType        int32                     `json:"update_type"`
	CommitHash        string                    `json:"commit_hash"`
	Message           *string                   `json:"message"`
	Platform          string                    `json:"platform"`
	CreatedAt         pgtype.Timestamptz        `json:"created_at"`
	CheckedAt         pgtype.Timestamptz        `json:"checked_at"`
	RolloutPercentage *int32                    `json:"rollout_percentage"`
	ControlUpdateID   *int64                    `json:"control_update_id"`
	PublishGroup      pgtype.UUID               `json:"publish_group"`
	AssetMapping      *types.UpdateAssetMapping `json:"asset_mapping"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	IsAdmin         bool               `json:"is_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LastConnectedAt pgtype.Timestamptz `json:"last_connected_at"`
	Enabled         bool               `json:"enabled"`
	SessionVersion  int32              `json:"session_version"`
}

type UserAppGrant struct {
	UserID           pgtype.UUID        `json:"user_id"`
	AppID            pgtype.UUID        `json:"app_id"`
	RoleID           pgtype.UUID        `json:"role_id"`
	ExtraPermissions []string           `json:"extra_permissions"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
