// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"xprem/internal/auditlog"
	"xprem/internal/types"
)

type AndroidCredential struct {
	ID                            pgtype.UUID        `json:"id"`
	AppIdentifierID               pgtype.UUID        `json:"app_identifier_id"`
	KeyAlias                      string             `json:"key_alias"`
	SealedKeystore                string             `json:"sealed_keystore"`
	SealedKeystorePassword        string             `json:"sealed_keystore_password"`
	SealedKeyPassword             string             `json:"sealed_key_password"`
	SealedGoogleServiceAccountKey *string            `json:"sealed_google_service_account_key"`
	GoogleServiceAccountEmail     *string            `json:"google_service_account_email"`
	GoogleServiceAccountProjectID *string            `json:"google_service_account_project_id"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
}

type ApiKey struct {
	ID         int64              `json:"id"`
	AppID      pgtype.UUID        `json:"app_id"`
	Name       string             `json:"name"`
	Hint       string             `json:"hint"`
	HashedKey  string             `json:"hashed_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	AllowedIps []netip.Prefix     `json:"allowed_ips"`
}

type ApiKeyBuildRule struct {
	ApiKeyID        int64       `json:"api_key_id"`
	AppID           pgtype.UUID `json:"app_id"`
	AppIdentifierID pgtype.UUID `json:"app_identifier_id"`
	Actions         []string    `json:"actions"`
}

type ApiKeyEnvironmentRule struct {
	ApiKeyID int64  `json:"api_key_id"`
	Pattern  string `json:"pattern"`
}

type ApiKeySubmitRule struct {
	ApiKeyID        int64       `json:"api_key_id"`
	AppID           pgtype.UUID `json:"app_id"`
	AppIdentifierID pgtype.UUID `json:"app_identifier_id"`
	Destination     string      `json:"destination"`
	Actions         []string    `json:"actions"`
}

type ApiKeyUpdateRule struct {
	ID        int64              `json:"id"`
	ApiKeyID  int64              `json:"api_key_id"`
	Pattern   string             `json:"pattern"`
	Actions   []string           `json:"actions"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type App struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	KeysMode           *string            `json:"keys_mode"`
	SealedPublicKey    *string            `json:"sealed_public_key"`
	SealedPrivateKey   *string            `json:"sealed_private_key"`
	PathPublicKey      *string            `json:"path_public_key"`
	PathPrivateKey     *string            `json:"path_private_key"`
	AwsSecretIDPublic  *string            `json:"aws_secret_id_public"`
	AwsSecretIDPrivate *string            `json:"aws_secret_id_private"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	GitUrl             *string            `json:"git_url"`
}

type AppIdentifier struct {
	ID          pgtype.UUID        `json:"id"`
	AppID       pgtype.UUID        `json:"app_id"`
	Platform    types.Platform     `json:"platform"`
	Identifier  string             `json:"identifier"`
	BuildNumber string             `json:"build_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AppStoreConnectApiKey struct {
	ID               pgtype.UUID        `json:"id"`
	AppID            pgtype.UUID        `json:"app_id"`
	KeyID            string             `json:"key_id"`
	IssuerID         string             `json:"issuer_id"`
	SealedPrivateKey string             `json:"sealed_private_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AuditExportState struct {
	ID             bool  `json:"id"`
	LastExportedID int64 `json:"last_exported_id"`
}

type AuditLogEvent struct {
	ID            int64              `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ActorType     string             `json:"actor_type"`
	ActorID       string             `json:"actor_id"`
	ActorDisplay  string             `json:"actor_display"`
	Action        string             `json:"action"`
	TargetType    string             `json:"target_type"`
	TargetID      string             `json:"target_id"`
	TargetDisplay string             `json:"target_display"`
	AppID         *string            `json:"app_id"`
	Outcome       string             `json:"outcome"`
	Ip            string             `json:"ip"`
	UserAgent     string             `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
}

type Blob struct {
	AppID       pgtype.UUID        `json:"app_id"`
	Hash        string             `json:"hash"`
	Size        int64              `json:"size"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Branch struct {
	ID        int64              `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Protected bool               `json:"protected"`
}

type Build struct {
	ID              pgtype.UUID             `json:"id"`
	AppID           pgtype.UUID             `json:"app_id"`
	AppIdentifierID pgtype.UUID             `json:"app_identifier_id"`
	Platform        types.Platform          `json:"platform"`
	ApplicationID   string                  `json:"application_id"`
	Status          types.BuildStatus       `json:"status"`
	ArtifactType    types.BuildArtifactType `json:"artifact_type"`
	Size            int64                   `json:"size"`
	Sha256          string                  `json:"sha256"`
	ArtifactKey     string                  `json:"artifact_key"`
	Metadata        []byte                  `json:"metadata"`
	ActorType       string                  `json:"actor_type"`
	ActorID         string                  `json:"actor_id"`
	ActorDisplay    string                  `json:"actor_display"`
	StartedAt       pgtype.Timestamptz      `json:"started_at"`
	FinishedAt      pgtype.Timestamptz      `json:"finished_at"`
	DurationMs      *int64                  `json:"duration_ms"`
	CreatedAt       pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz      `json:"updated_at"`
	ReadyAt         pgtype.Timestamptz      `json:"ready_at"`
}

type BuildArtifactCleanup struct {
	ID              int64                   `json:"id"`
	BuildID         pgtype.UUID             `json:"build_id"`
	Platform        types.Platform          `json:"platform"`
	AppIdentifierID pgtype.UUID             `json:"app_identifier_id"`
	ArtifactType    types.BuildArtifactType `json:"artifact_type"`
	DueAt           pgtype.Timestamptz      `json:"due_at"`
	Attempts        int32                   `json:"attempts"`
	LastError       *string                 `json:"last_error"`
	CreatedAt       pgtype.Timestamptz      `json:"created_at"`
}

type BuildCacheCleanup struct {
	ID              pgtype.UUID               `json:"id"`
	AppID           pgtype.UUID               `json:"app_id"`
	AppIdentifierID pgtype.UUID               `json:"app_identifier_id"`
	Namespace       types.BuildCacheNamespace `json:"namespace"`
	Size            int64                     `json:"size"`
	DueAt           pgtype.Timestamptz        `json:"due_at"`
}

type BuildCacheObject struct {
	ID              pgtype.UUID               `json:"id"`
	AppID           pgtype.UUID               `json:"app_id"`
	AppIdentifierID pgtype.UUID               `json:"app_identifier_id"`
	Namespace       types.BuildCacheNamespace `json:"namespace"`
	CacheKey        string                    `json:"cache_key"`
	Size            int64                     `json:"size"`
	Sha256          string                    `json:"sha256"`
	CreatedAt       pgtype.Timestamptz        `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz        `json:"expires_at"`
	PublishedAt     pgtype.Timestamptz        `json:"published_at"`
}

type BuildLogChunk struct {
	BuildID    pgtype.UUID        `json:"build_id"`
	ByteOffset int32              `json:"byte_offset"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BuildShare struct {
	ID        pgtype.UUID        `json:"id"`
	BuildID   pgtype.UUID        `json:"build_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type BuildStagingSweep struct {
	BuildID pgtype.UUID        `json:"build_id"`
	SweptAt pgtype.Timestamptz `json:"swept_at"`
}

type BundlePatch struct {
	BranchID         int64                   `json:"branch_id"`
	TargetUpdateID   int64                   `json:"target_update_id"`
	SourceUpdateID   int64                   `json:"source_update_id"`
	Status           types.BundlePatchStatus `json:"status"`
	Reason           *string                 `json:"reason"`
	PatchSize        *int64                  `json:"patch_size"`
	FullDownloadSize *int64                  `json:"full_download_size"`
	Attempts         int32                   `json:"attempts"`
	CreatedAt        pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz      `json:"updated_at"`
}

type Channel struct {
	ID                   int64              `json:"id"`
	AppID                pgtype.UUID        `json:"app_id"`
	BranchID             *int64             `json:"branch_id"`
	Name                 string             `json:"name"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	BranchSurfingEnabled bool               `json:"branch_surfing_enabled"`
	BranchSurfingPattern string             `json:"branch_surfing_pattern"`
	EnvironmentID        pgtype.UUID        `json:"environment_id"`
}

type ChannelRollout struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       int64              `json:"channel_id"`
	RolloutBranchID int64              `json:"rollout_branch_id"`
	Percentage      int32              `json:"percentage"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DeviceHealthOutbox struct {
	ID               int64              `json:"id"`
	EventType        string             `json:"event_type"`
	AppID            pgtype.UUID        `json:"app_id"`
	EasClientID      pgtype.UUID        `json:"eas_client_id"`
	UpdateID         pgtype.UUID        `json:"update_id"`
	PreviousUpdateID pgtype.UUID        `json:"previous_update_id"`
	FailureType      *string            `json:"failure_type"`
	FatalError       string             `json:"fatal_error"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
}

type DeviceIdentity struct {
	AppID                   pgtype.UUID        `json:"app_id"`
	EasClientID             pgtype.UUID        `json:"eas_client_id"`
	Metadata                []byte             `json:"metadata"`
	CountryCode             *string            `json:"country_code"`
	City                    *string            `json:"city"`
	Lat                     *float64           `json:"lat"`
	Lng                     *float64           `json:"lng"`
	FirstSeenAt             pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	CurrentUpdateID         pgtype.UUID        `json:"current_update_id"`
	DeviceModel             *string            `json:"device_model"`
	OsName                  *string            `json:"os_name"`
	OsVersion               *string            `json:"os_version"`
	BranchName              *string            `json:"branch_name"`
	RuntimeVersion          *string            `json:"runtime_version"`
	Platform                *string            `json:"platform"`
	PublishGroup            pgtype.UUID        `json:"publish_group"`
	AppVersion              *string            `json:"app_version"`
	CurrentUpdateObservedAt pgtype.Timestamptz `json:"current_update_observed_at"`
	CurrentUpdateArrivedAt  pgtype.Timestamptz `json:"current_update_arrived_at"`
}

type DeviceUpdateFailure struct {
	AppID       pgtype.UUID        `json:"app_id"`
	EasClientID pgtype.UUID        `json:"eas_client_id"`
	UpdateID    pgtype.UUID        `json:"update_id"`
	FailureType string             `json:"failure_type"`
	FatalError  string             `json:"fatal_error"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
}

type DeviceUpdateRuntimeState struct {
	AppID         pgtype.UUID        `json:"app_id"`
	EasClientID   pgtype.UUID        `json:"eas_client_id"`
	UpdateID      pgtype.UUID        `json:"update_id"`
	LastStartedAt pgtype.Timestamptz `json:"last_started_at"`
	LastCrashedAt pgtype.Timestamptz `json:"last_crashed_at"`
}

type EnterpriseLicense struct {
	Singleton              bool               `json:"singleton"`
	LicenseKey             string             `json:"license_key"`
	SealedActivationSecret string             `json:"sealed_activation_secret"`
	OrgName                string             `json:"org_name"`
	PlanCode               string             `json:"plan_code"`
	SubscriptionStartAt    pgtype.Timestamptz `json:"subscription_start_at"`
	SubscriptionEndAt      pgtype.Timestamptz `json:"subscription_end_at"`
	SubscriptionRenewalAt  pgtype.Timestamptz `json:"subscription_renewal_at"`
	ActivatedAt            pgtype.Timestamptz `json:"activated_at"`
	LastValidatedAt        pgtype.Timestamptz `json:"last_validated_at"`
	ValidationFailedAt     pgtype.Timestamptz `json:"validation_failed_at"`
	ValidationErrorCode    *string            `json:"validation_error_code"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Environment struct {
	ID        pgtype.UUID        `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EnvironmentVar struct {
	ID            pgtype.UUID        `json:"id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	Key           string             `json:"key"`
	IsPublic      bool               `json:"is_public"`
	SealedValue   string             `json:"sealed_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type IdentitySchema struct {
	AppID     pgtype.UUID        `json:"app_id"`
	Key       string             `json:"key"`
	ValueType string             `json:"value_type"`
	MaxLength int32              `json:"max_length"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdentityValueStat struct {
	AppID       pgtype.UUID        `json:"app_id"`
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	DeviceCount int64              `json:"device_count"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type IosCertificate struct {
	ID                        pgtype.UUID              `json:"id"`
	SealedCertificate         string                   `json:"sealed_certificate"`
	SealedCertificatePassword string                   `json:"sealed_certificate_password"`
	CommonName                string                   `json:"common_name"`
	SerialNumber              string                   `json:"serial_number"`
	FingerprintSha1           string                   `json:"fingerprint_sha1"`
	CertificateType           types.IosCertificateType `json:"certificate_type"`
	TeamID                    string                   `json:"team_id"`
	ExpiresAt                 pgtype.Timestamptz       `json:"expires_at"`
	CreatedAt                 pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz       `json:"updated_at"`
}

type IosDeviceInvitation struct {
	ID                    pgtype.UUID        `json:"id"`
	AppID                 pgtype.UUID        `json:"app_id"`
	TokenHash             string             `json:"token_hash"`
	Challenge             string             `json:"challenge"`
	ClaimToken            pgtype.UUID        `json:"claim_token"`
	Label                 string             `json:"label"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ClaimedAt             pgtype.Timestamptz `json:"claimed_at"`
	ConsumedAt            pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	CreatedByActorType    auditlog.ActorType `json:"created_by_actor_type"`
	CreatedByActorID      string             `json:"created_by_actor_id"`
	CreatedByActorDisplay string             `json:"created_by_actor_display"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	RegistrationID        pgtype.UUID        `json:"registration_id"`
}

type IosDeviceRegistration struct {
	ID            pgtype.UUID                       `json:"id"`
	InvitationID  pgtype.UUID                       `json:"invitation_id"`
	Udid          string                            `json:"udid"`
	DeviceName    string                            `json:"device_name"`
	Product       string                            `json:"product"`
	OsVersion     string                            `json:"os_version"`
	Status        types.IosDeviceRegistrationStatus `json:"status"`
	AppleDeviceID *string                           `json:"apple_device_id"`
	Error         *string                           `json:"error"`
	CreatedAt     pgtype.Timestamptz                `json:"created_at"`
}

type IosSigningSetting struct {
	AppIdentifierID pgtype.UUID          `json:"app_identifier_id"`
	Mode            types.IosSigningMode `json:"mode"`
	CertificateID   pgtype.UUID          `json:"certificate_id"`
	CreatedAt       pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz   `json:"updated_at"`
}

type OauthAuthorizationCode struct {
	ID            pgtype.UUID        `json:"id"`
	ClientID      pgtype.UUID        `json:"client_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	Scope         string             `json:"scope"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
}

type OauthClient struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	RedirectUris []string           `json:"redirect_uris"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Permissions []string           `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RuntimeVersion struct {
	ID        int64              `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Version   string             `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ServerInstance struct {
	Singleton bool               `json:"singleton"`
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SsoConfig struct {
	Singleton            bool               `json:"singleton"`
	Issuer               string             `json:"issuer"`
	ClientID             string             `json:"client_id"`
	SealedClientSecret   string             `json:"sealed_client_secret"`
	ProviderName         string             `json:"provider_name"`
	Scopes               string             `json:"scopes"`
	Enabled              bool               `json:"enabled"`
	AllowedEmailDomains  []string           `json:"allowed_email_domains"`
	AllowedGroups        []string           `json:"allowed_groups"`
	GroupsClaim          string             `json:"groups_claim"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	TrustUnverifiedEmail bool               `json:"trust_unverified_email"`
	ManualUserValidation bool               `json:"manual_user_validation"`
}

type SsoIdentity struct {
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       string             `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type Update struct {
	ID                int64                     `json:"id"`
	UpdateUuid        pgtype.UUID               `json:"update_uuid"`
	BranchID          int64                     `json:"branch_id"`
	RuntimeVersionID  int64                     `json:"runtime_version_id"`
	UpdateType        int32                     `json:"update_type"`
	CommitHash        string                    `json:"commit_hash"`
	Message           *string                   `json:"message"`
	Platform          types.Platform            `json:"platform"`
	CreatedAt         pgtype.Timestamptz        `json:"created_at"`
	CheckedAt         pgtype.Timestamptz        `json:"checked_at"`
	RolloutPercentage *int32                    `json:"rollout_percentage"`
	ControlUpdateID   *int64                    `json:"control_update_id"`
	PublishGroup      pgtype.UUID               `json:"publish_group"`
	AssetMapping      *types.UpdateAssetMapping `json:"asset_mapping"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	IsAdmin         bool               `json:"is_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LastConnectedAt pgtype.Timestamptz `json:"last_connected_at"`
	Enabled         bool               `json:"enabled"`
	SessionVersion  int32              `json:"session_version"`
}

type UserAppGrant struct {
	UserID           pgtype.UUID        `json:"user_id"`
	AppID            pgtype.UUID        `json:"app_id"`
	RoleID           pgtype.UUID        `json:"role_id"`
	ExtraPermissions []string           `json:"extra_permissions"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
