// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observe_error_group_sweep.sql

package pgdb

import (
	"context"
)

const getObserveErrorGroupSweepState = `-- name: GetObserveErrorGroupSweepState :one
SELECT state FROM observe_error_group_sweep_state WHERE id = TRUE
`

func (q *Queries) GetObserveErrorGroupSweepState(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getObserveErrorGroupSweepState)
	var state []byte
	err := row.Scan(&state)
	return state, err
}

const saveObserveErrorGroupSweepState = `-- name: SaveObserveErrorGroupSweepState :exec
UPDATE observe_error_group_sweep_state SET state = $1::jsonb WHERE id = TRUE
`

func (q *Queries) SaveObserveErrorGroupSweepState(ctx context.Context, state []byte) error {
	_, err := q.db.Exec(ctx, saveObserveErrorGroupSweepState, state)
	return err
}
