// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serving_updates.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"xprem/internal/types"
)

const getLatestUpdateFeed = `-- name: GetLatestUpdateFeed :many
WITH heads AS (
    SELECT DISTINCT ON (u.branch_id, u.runtime_version_id, u.platform)
           u.branch_id, u.id,
           CASE WHEN u.rollout_percentage IS NOT NULL THEN u.control_update_id END AS control_id
    FROM updates u
    JOIN branches b ON b.id = u.branch_id
    JOIN runtime_versions rv ON rv.id = u.runtime_version_id
    WHERE b.app_id = $1
      AND ($12::text = '' OR b.name = $12)
      AND ($13::text = '' OR rv.version = $13)
      AND ($14::text = '' OR u.platform = $14)
      AND u.checked_at IS NOT NULL
    ORDER BY u.branch_id, u.runtime_version_id, u.platform, u.id DESC
), served AS (
    SELECT branch_id, id FROM heads
    UNION
    SELECT branch_id, control_id FROM heads WHERE control_id IS NOT NULL
)
SELECT u.id, u.update_uuid, u.update_type, u.created_at, u.commit_hash,
       u.platform, u.message, u.rollout_percentage, u.control_update_id,
       u.publish_group, u.branch_id, b.name AS branch_name,
       rv.version AS runtime_version
FROM updates u
JOIN branches b ON u.branch_id = b.id
JOIN runtime_versions rv ON u.runtime_version_id = rv.id
WHERE (u.branch_id, u.id) IN (SELECT branch_id, id FROM served)
  AND b.app_id = $1
  AND u.checked_at IS NOT NULL
  AND ($2::text = '' OR u.update_uuid::text ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR u.publish_group::text ILIKE '%' || $3 || '%')
  AND ($4::text = '' OR u.commit_hash ILIKE '%' || $4 || '%')
  AND ($5::timestamptz IS NULL OR u.created_at >= $5)
  AND ($6::timestamptz IS NULL OR u.created_at <= $6)
  AND (
    NOT $7::boolean
    OR (u.created_at, u.branch_id, u.id) < ($8::timestamptz, $9::bigint, $10::bigint)
  )
ORDER BY u.created_at DESC, u.branch_id DESC, u.id DESC
LIMIT $11::int
`

type GetLatestUpdateFeedParams struct {
	AppID           pgtype.UUID        `json:"app_id"`
	UpdateUuid      string             `json:"update_uuid"`
	PublishGroup    string             `json:"publish_group"`
	CommitHash      string             `json:"commit_hash"`
	CreatedFrom     pgtype.Timestamptz `json:"created_from"`
	CreatedTo       pgtype.Timestamptz `json:"created_to"`
	HasCursor       bool               `json:"has_cursor"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorBranchID  int64              `json:"cursor_branch_id"`
	CursorUpdateID  int64              `json:"cursor_update_id"`
	RowLimit        int32              `json:"row_limit"`
	Branch          string             `json:"branch"`
	RuntimeVersion  string             `json:"runtime_version"`
	Platform        string             `json:"platform"`
}

type GetLatestUpdateFeedRow struct {
	ID                int64              `json:"id"`
	UpdateUuid        pgtype.UUID        `json:"update_uuid"`
	UpdateType        int32              `json:"update_type"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CommitHash        string             `json:"commit_hash"`
	Platform          types.Platform     `json:"platform"`
	Message           *string            `json:"message"`
	RolloutPercentage *int32             `json:"rollout_percentage"`
	ControlUpdateID   *int64             `json:"control_update_id"`
	PublishGroup      pgtype.UUID        `json:"publish_group"`
	BranchID          int64              `json:"branch_id"`
	BranchName        string             `json:"branch_name"`
	RuntimeVersion    string             `json:"runtime_version"`
}

// The serving inventory is picked before pagination: an older runtime remains
// served even when many newer publishes use another runtime. Active rollout
// controls also remain served, including rollback-to-embedded controls.
func (q *Queries) GetLatestUpdateFeed(ctx context.Context, arg GetLatestUpdateFeedParams) ([]GetLatestUpdateFeedRow, error) {
	rows, err := q.db.Query(ctx, getLatestUpdateFeed,
		arg.AppID,
		arg.UpdateUuid,
		arg.PublishGroup,
		arg.CommitHash,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorBranchID,
		arg.CursorUpdateID,
		arg.RowLimit,
		arg.Branch,
		arg.RuntimeVersion,
		arg.Platform,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestUpdateFeedRow
	for rows.Next() {
		var i GetLatestUpdateFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UpdateUuid,
			&i.UpdateType,
			&i.CreatedAt,
			&i.CommitHash,
			&i.Platform,
			&i.Message,
			&i.RolloutPercentage,
			&i.ControlUpdateID,
			&i.PublishGroup,
			&i.BranchID,
			&i.BranchName,
			&i.RuntimeVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
